version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    build:
      context: ./docker/db
    image: "postgres:latest"
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - 5450:5432