openapi: 3.0.3
info:    
  title: Puppy Playdate Finder API
  version: v1 
paths: 
  /users:
    x-controller: users
    post:
      x-operation: createUser
      tags:
        - Users
      summary: create a user's account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object  
              required: 
                - username
                - password
                - email
              properties: 
                parentName: 
                  type: string
                parentBirthday: 
                  type: string
                  format: date-time
                petName: 
                  type: string
                bio:
                  type: string
                location:
                  type: string 
                username: 
                  type: string
                password:
                  type: string
                  format: password
                email: 
                  type: string
                tags: 
                  type: array
                  items:
                    type: string
            example:
              parentName: Sarah Miller
              parentBirthday: 1995-01-01
              petName: Luna
              bio: a cute dog looking for fun friends
              location: Los Angeles, CA, USA  
              username: sarahm098
              password: password123
              email: sarahm@gmail.com  
              tags:
                - cute
                - collie
                - energetic
      responses:
        201:
          description: User created.
        400:
          description: Invalid request.
        409:
          description: User already exists. 
  /users/{userId}:
    x-controller: users
    parameters:
      - $ref: '#/components/parameters/PathId'
    patch:
      x-operation: updateUser
      tags:
        - Users
      security:
        - cookieAuth: []
      summary: update a user's account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object  
              required: 
                - username
                - password
                - email
              properties: 
                userId:
                  type: string
                  readOnly: true
                parentName: 
                  type: string
                parentBirthday: 
                  type: string
                  format: date-time
                petName: 
                  type: string
                bio:
                  type: string
                location:
                  type: string 
                username: 
                  type: string
                password:
                  type: string
                  format: password
                email: 
                  type: string
                tags: 
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: Successfully updated.
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
    delete:
      x-operation: deleteUser
      tags:
        - Users
      summary: delete a user's account
      responses:
        204:
          description: User deleted.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
  /users/{userId}/pics:
    x-controller: users
    parameters:
      - $ref: '#/components/parameters/PathId'
    post:
      x-operation: uploadPicture
      tags:
        - Users
      security:
        - cookieAuth: []
      summary: upload a picture
      requestBody:
        $ref: '#/components/requestBodies/UploadPicture'
      responses:
        201:
          description: Picture uploaded successfully.
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
        404:
          description: Profile not found.
  /users/{userId}/pics/{pic_id}:
    x-controller: users
    parameters:
      - $ref: '#/components/parameters/PathId'
      - $ref: '#/components/parameters/PathPicId'
    delete:
      x-operation: deletePicture
      tags:
        - Users
      security:
        - cookieAuth: []
      summary: delete a picture
      responses:
        204:
          description: Picture deleted.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
  /authentication/login:
    x-controller: authentication
    put:
      x-operation: login
      tags:
        - Authentication
      summary: login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username: 
                  type: string
                password:
                  type: string
                  format: password
            example:
              username: doglover1234
              password: agreatpassword
      responses:
        200:
          description: Authenticated.
        400:
          description: Invalid request.
        403:
          description: Access denied.
  /authentication/logout:
    x-controller: authentication
    put:
      x-operation: logout
      tags:
        - Authentication
      summary: log a user out
      responses:
        200:
          description: Logged out.
        403:
          description: Access denied.
  /chats:
    post:
      tags:
        - Chats
      security:
        - cookieAuth: []
      summary: create a chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chat'
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
  /chats/{chat_id}:
    parameters:
      - $ref: '#/components/parameters/PathChatId'
    get:
      tags:
        - Chats
      security:
        - cookieAuth: []
      summary: get a specific chat
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
    put:
      tags:
        - Chats
      security:
        - cookieAuth: []
      summary: update a chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Chat'
      responses:
        200:
          description: Success.
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
    delete:
      tags:
        - Chats
      security:
        - cookieAuth: []
      summary: delete a chat
      responses:
        204:
          description: Chat deleted.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
  /chats/{chat_id}/send:
    parameters:
      - $ref: '#/components/parameters/PathChatId'
    put:
      tags:
        - Chats
      security:
        - cookieAuth: []
      summary: send a message
      requestBody:
        $ref: '#/components/requestBodies/SendMessage'
      responses:
        200:
          description: Success.
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
components: 
  parameters: 
    PathId: 
      name: userId
      in: path
      required: true
      schema:
        type: string
    PathChatId: 
      name: chat_id
      in: path
      required: true
      schema:
        type: string
    PathPicId:
      name: pic_id
      in: path
      required: true
      schema:
        type: string
  requestBodies: 
    SetChat:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Chat'
    SendMessage:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Message'
    UploadPicture:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pic'
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: todoSessionId 
  schemas:
    Pic:
      type: object 
      properties: 
        data:
          type: string
          format: binary
        size:
          type: number
        name:
          type: string
    User:
      type: object 
      properties: 
        userId:
          type: string
          readOnly: true
        parentName: 
          type: string
        parentBirthday: 
          type: string
          format: date-time
        petName: 
          type: string
        bio:
          type: string
        location:
          type: string 
        username: 
          type: string
        password:
          type: string
          format: password
        email: 
          type: string
        tags: 
          type: array
          items:
            type: string
    Message:
      type: object 
      properties: 
        messageId: 
          type: string
          nullable: true
          readOnly: true
        message: 
          type: string
        receivingUser:
          type: string
        sendingUser:
          type: string
    Chat:
      type: object
      properties:
        chatId:
          type: string
          readOnly: true
        messages: 
          type: array 
          items: 
            $ref: '#/components/schemas/Message'
